title: "아프리카도서관"
author: "africalib"
email: "africalibrary21@gmail.com"
url: "https://africalib.github.io"
description: "africalib"
permalink: /:slug.html
#theme: africalib

theme_config:
  back_home_text: ".." # customize text for homepage link in post layout
  date_format: "%Y-%m-%d" # customize how date is formatted
  show_description: true # show blog description in home page

sass:
  style: expanded

plugins:
  - jekyll-feed
  - jekyll-seo-tag

markdown: kramdown
kramdown:
    highlighter: rouge
    syntax_highlighter_opts:
        block:
            line_numbers: false